import type { Kit } from './types'

// Seed data — in production, pulled from registry/kits.json + GitHub API
export const kits: Kit[] = [
  {
    id: '092d35eb-eb8b-4ce2-a57b-6788657263f3',
    name: 'Anthropic Skills',
    description: 'Public repository for Agent Skills',
    source: 'github',
    repoUrl: 'https://github.com/anthropics/skills',
    owner: 'anthropics',
    stars: 93508,
    forks: 10019,
    lastUpdated: '2026-03-15',
    creator: '@anthropic',
    createdAt: '2025-06-16',
    compatibility: ['claude-code', 'claude', 'openai-codex', 'github-copilot', 'vs-code', 'cursor', 'gemini-cli', 'roo-code', 'goose', 'openclaw'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skillCount: 17,
  },
  {
    id: '984c0770-c52b-4d3a-b6b5-4057f22abe00',
    name: 'Awesome CursorRules',
    description: 'Configuration files that enhance Cursor AI editor experience with custom rules and behaviors',
    source: 'github',
    repoUrl: 'https://github.com/PatrickJS/awesome-cursorrules',
    owner: 'PatrickJS',
    stars: 38457,
    forks: 3256,
    lastUpdated: '2026-03-15',
    creator: '@PatrickJS',
    createdAt: '2024-09-01',
    compatibility: ['cursor', 'windsurf'],
    trustTier: 'community',
    detectedFiles: ['.cursorrules'],
    skillCount: 179,
  },
  {
    id: '06465063-6a42-410f-9240-ee3ebce78bc9',
    name: 'gstack',
    description: "Use Garry Tan's exact Claude Code setup: 6 opinionated tools that serve as CEO, Eng Manager, Release Manager and QA Engineer",
    source: 'github',
    repoUrl: 'https://github.com/garrytan/gstack',
    owner: 'garrytan',
    stars: 10595,
    forks: 1260,
    lastUpdated: '2026-03-15',
    creator: '@garrytan',
    createdAt: '2026-01-15',
    compatibility: ['claude-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'CLAUDE.md'],
    skillCount: 8,
  },
  {
    id: '984d745e-07a7-45cf-979f-43563b605061',
    name: 'Awesome Copilot',
    description: 'Community-contributed instructions, agents, skills, and configurations to help you make the most of GitHub Copilot.',
    source: 'github',
    repoUrl: 'https://github.com/github/awesome-copilot',
    owner: 'github',
    stars: 25178,
    forks: 2882,
    lastUpdated: '2026-03-15',
    creator: '@github',
    createdAt: '2025-06-11',
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'AGENTS.md'],
    skillCount: 100,
  },
  {
    id: 'd376e7d0-5191-4fe9-8802-340721587088',
    name: 'Vercel Agent Skills',
    description: "Vercel's official collection of agent skills",
    source: 'github',
    repoUrl: 'https://github.com/vercel-labs/agent-skills',
    owner: 'vercel-labs',
    stars: 22997,
    forks: 2067,
    lastUpdated: '2026-03-15',
    creator: '@vercel',
    createdAt: '2025-12-08',
    compatibility: ['claude-code', 'cursor', 'github-copilot', 'vs-code', 'gemini-cli'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'AGENTS.md', 'CLAUDE.md'],
    skillCount: 5,
  },
  {
    id: 'bc31b9a3-0d7e-43c6-a43e-d563fb629768',
    name: 'GitHub Copilot for Azure',
    description: 'GitHub Copilot for Azure',
    source: 'github',
    repoUrl: 'https://github.com/microsoft/GitHub-Copilot-for-Azure',
    owner: 'microsoft',
    stars: 154,
    forks: 100,
    lastUpdated: '2026-03-14',
    creator: '@microsoft',
    createdAt: '2024-10-01',
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skillCount: 25,
  },
  {
    id: 'c1330bf7-19dd-4830-a6de-9ed3d27b7aba',
    name: 'Claude Scientific Skills',
    description: 'A set of ready to use Agent Skills for research, science, engineering, analysis, finance and writing.',
    source: 'github',
    repoUrl: 'https://github.com/K-Dense-AI/claude-scientific-skills',
    owner: 'K-Dense-AI',
    stars: 14879,
    forks: 1639,
    lastUpdated: '2026-03-15',
    creator: '@K-Dense-AI',
    createdAt: '2025-10-19',
    compatibility: ['claude-code', 'claude'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skillCount: 200,
  },
]
